version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: "tri-menu"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
